_target_: src.models.klue_module.KLUEModule

model_name: "klue/bert-base"

loss_fn:
  _target_: src.models.components.focal_loss.FocalLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-5

scheduler:
  _target_: transformers.get_linear_schedule_with_warmup
  _partial_: true
