_target_: src.models.klue_module.KLUEModule

model_name: "klue/bert-base"

loss_fn:
  _target_: src.models.components.focal_loss.FocalLoss
  alpha: 1.
  gamma: 2
  reduction: "mean"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
