_target_: src.models.st_module.SemanticTypingModule

model_name: "klue/roberta-base"

do_prob: 0.1

loss_fn:
  _target_: src.models.components.focal_loss.FocalLoss
  alpha: 1.
  gamma: 2
  reduction: "mean"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5e-6

scheduler:
  _target_: transformers.get_linear_schedule_with_warmup
  _partial_: true
