_target_: src.models.stacking_module.StackingModule

net:
  _target_: src.models.components.plain_automodel.Encoder
  model_name: "klue/bert-base"
  num_labels: 30

binary_loss_fn:
  _target_: torch.nn.CrossEntropyLoss
multiclass_loss_fn:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: 0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
