_target_: src.models.klue_module.KLUEModule

net:
  _target_: src.models.components.yeonsu_encoder.YeonsuEncoder
  model_name: "klue/roberta-large"
  num_labels: 30

loss_fn:
  _target_: torch.nn.CrossEntropyLoss # 원하는 Loss function으로 변경 가능합니다. 
  # _target_: src.models.components.focal_loss.FocalLoss
  # label_smoothing: 0.0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2.306e-6

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10