# @package _global_

defaults:
  - _self_
  - data: yeonsu # choose datamodule with `test_dataloader()` for evaluation
  - model: yeonsu
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "inference"

tags: ["prediction"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}train/runs/${model.net.model_name}/checkpoints/best_model.ckpt
